title: "Janam Shrestha"
description: "Personal Portfolio and Projects"
baseurl: "" # leave blank for username.github.io
url: "https://xzanam.github.io"
theme: jekyll-theme-minimal
markdown: kramdown

# Navigation links
nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"

# Social
social_links:
  github: "https://github.com/xzanam"
  linkedin: "https://linkedin.com/in/janam-shrestha"

